<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class MovieSeeder extends Seeder
{
    public function run()
    {
        $movies = [
            [
                'title' => 'The Dark Knight',
                'title_vi' => 'Kỵ sĩ bóng đêm',
                'description' => 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
                'description_vi' => 'Khi kẻ thù được gọi là Joker gây ra sự tàn phá và hỗn loạn cho người dân Gotham, Batman phải chấp nhận một trong những thử thách tâm lý và thể chất lớn nhất về khả năng chống lại bất công của mình.',
                'poster' => 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=400&h=600&fit=crop',
                'backdrop' => 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=1200&h=600&fit=crop',
                'trailer' => 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
                'release_date' => '2008-07-18',
                'duration' => 152,
                'country' => 'USA',
                'language' => 'English',
                'director' => 'Christopher Nolan',
                'cast' => json_encode(['Christian Bale', 'Heath Ledger', 'Aaron Eckhart']),
                'rating' => 9.0,
                'featured' => true,
                'slug' => 'the-dark-knight',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Inception',
                'title_vi' => 'Kẻ đánh cắp giấc mơ',
                'description' => 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
                'description_vi' => 'Một tên trộm ăn cắp bí mật công ty thông qua việc sử dụng công nghệ chia sẻ giấc mơ được giao nhiệm vụ ngược lại là gieo ý tưởng vào tâm trí của một CEO.',
                'poster' => 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=600&fit=crop',
                'backdrop' => 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=1200&h=600&fit=crop',
                'trailer' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
                'release_date' => '2010-07-16',
                'duration' => 148,
                'country' => 'USA',
                'language' => 'English',
                'director' => 'Christopher Nolan',
                'cast' => json_encode(['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page']),
                'rating' => 8.8,
                'featured' => true,
                'slug' => 'inception',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Shawshank Redemption',
                'title_vi' => 'Nhà tù Shawshank',
                'description' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
                'description_vi' => 'Hai người đàn ông bị giam cầm kết nối với nhau trong nhiều năm, tìm thấy sự an ủi và cuối cùng là sự cứu chuộc thông qua những hành động tử tế.',
                'poster' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
                'backdrop' => 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=1200&h=600&fit=crop',
                'trailer' => 'https://www.youtube.com/watch?v=6hB3S9bIaco',
                'release_date' => '1994-09-22',
                'duration' => 142,
                'country' => 'USA',
                'language' => 'English',
                'director' => 'Frank Darabont',
                'cast' => json_encode(['Tim Robbins', 'Morgan Freeman', 'Bob Gunton']),
                'rating' => 9.3,
                'featured' => false,
                'slug' => 'the-shawshank-redemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pulp Fiction',
                'title_vi' => 'Pulp Fiction',
                'description' => 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
                'description_vi' => 'Cuộc sống của hai sát thủ mafia, một võ sĩ quyền Anh, một tên côn đồ và vợ anh ta, cùng một cặp cướp nhà hàng đan xen trong bốn câu chuyện về bạo lực và sự cứu chuộc.',
                'poster' => 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=600&fit=crop',
                'backdrop' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=600&fit=crop',
                'trailer' => 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
                'release_date' => '1994-10-14',
                'duration' => 154,
                'country' => 'USA',
                'language' => 'English',
                'director' => 'Quentin Tarantino',
                'cast' => json_encode(['John Travolta', 'Uma Thurman', 'Samuel L. Jackson']),
                'rating' => 8.9,
                'featured' => false,
                'slug' => 'pulp-fiction',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Godfather',
                'title_vi' => 'Bố già',
                'description' => 'The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant son.',
                'description_vi' => 'Người cha già của một triều đại tội phạm có tổ chức ở thành phố New York thời hậu chiến chuyển giao quyền kiểm soát đế chế bí mật của mình cho người con trai miễn cưỡng.',
                'poster' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
                'backdrop' => 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=1200&h=600&fit=crop',
                'trailer' => 'https://www.youtube.com/watch?v=sY1S34973zA',
                'release_date' => '1972-03-24',
                'duration' => 175,
                'country' => 'USA',
                'language' => 'English',
                'director' => 'Francis Ford Coppola',
                'cast' => json_encode(['Marlon Brando', 'Al Pacino', 'James Caan']),
                'rating' => 9.2,
                'featured' => true,
                'slug' => 'the-godfather',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fight Club',
                'title_vi' => 'Câu lạc bộ đấm bốc',
                'description' => 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much bigger.',
                'description_vi' => 'Một nhân viên văn phòng mất ngủ và một người làm xà phòng vô tư lự thành lập một câu lạc bộ đấm bốc ngầm phát triển thành một thứ lớn hơn nhiều.',
                'poster' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
                'backdrop' => 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&h=600&fit=crop',
                'trailer' => 'https://www.youtube.com/watch?v=SUXWAEX2jlg',
                'release_date' => '1999-10-15',
                'duration' => 139,
                'country' => 'USA',
                'language' => 'English',
                'director' => 'David Fincher',
                'cast' => json_encode(['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter']),
                'rating' => 8.8,
                'featured' => false,
                'slug' => 'fight-club',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Forrest Gump',
                'title_vi' => 'Forrest Gump',
                'description' => 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
                'description_vi' => 'Các nhiệm kỳ tổng thống của Kennedy và Johnson, Chiến tranh Việt Nam, vụ bê bối Watergate và các sự kiện lịch sử khác diễn ra từ góc nhìn của một người đàn ông Alabama có IQ 75.',
                'poster' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
                'backdrop' => 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&h=600&fit=crop',
                'trailer' => 'https://www.youtube.com/watch?v=bLvqoHBptjg',
                'release_date' => '1994-07-06',
                'duration' => 142,
                'country' => 'USA',
                'language' => 'English',
                'director' => 'Robert Zemeckis',
                'cast' => json_encode(['Tom Hanks', 'Robin Wright', 'Gary Sinise']),
                'rating' => 8.8,
                'featured' => false,
                'slug' => 'forrest-gump',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Matrix',
                'title_vi' => 'Ma trận',
                'description' => 'A computer programmer discovers that reality as he knows it is a simulation created by machines, and joins a rebellion to break free.',
                'description_vi' => 'Một lập trình viên máy tính phát hiện ra rằng thực tại mà anh ta biết là một mô phỏng được tạo ra bởi máy móc, và tham gia cuộc nổi dậy để thoát khỏi nó.',
                'poster' => 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=600&fit=crop',
                'backdrop' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=600&fit=crop',
                'trailer' => 'https://www.youtube.com/watch?v=m8e-FF8MsqU',
                'release_date' => '1999-03-31',
                'duration' => 136,
                'country' => 'USA',
                'language' => 'English',
                'director' => 'Lana Wachowski',
                'cast' => json_encode(['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss']),
                'rating' => 8.7,
                'featured' => true,
                'slug' => 'the-matrix',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Goodfellas',
                'title_vi' => 'Những kẻ tốt',
                'description' => 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.',
                'description_vi' => 'Câu chuyện về Henry Hill và cuộc sống của anh ta trong băng đảng, bao gồm mối quan hệ với vợ Karen Hill và các đối tác băng đảng Jimmy Conway và Tommy DeVito.',
                'poster' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
                'backdrop' => 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&h=600&fit=crop',
                'trailer' => 'https://www.youtube.com/watch?v=2ilzidiJ8sQ',
                'release_date' => '1990-09-19',
                'duration' => 146,
                'country' => 'USA',
                'language' => 'English',
                'director' => 'Martin Scorsese',
                'cast' => json_encode(['Robert De Niro', 'Ray Liotta', 'Joe Pesci']),
                'rating' => 8.7,
                'featured' => false,
                'slug' => 'goodfellas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Silence of the Lambs',
                'title_vi' => 'Sự im lặng của bầy cừu',
                'description' => 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',
                'description_vi' => 'Một học viên FBI trẻ tuổi phải nhận sự giúp đỡ từ một kẻ giết người ăn thịt bị giam cầm và thao túng để giúp bắt một kẻ giết người hàng loạt khác.',
                'poster' => 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=600&fit=crop',
                'backdrop' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=600&fit=crop',
                'trailer' => 'https://www.youtube.com/watch?v=W6Mm8Sbe__o',
                'release_date' => '1991-02-14',
                'duration' => 118,
                'country' => 'USA',
                'language' => 'English',
                'director' => 'Jonathan Demme',
                'cast' => json_encode(['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn']),
                'rating' => 8.6,
                'featured' => false,
                'slug' => 'the-silence-of-the-lambs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        $hasCastColumn = Schema::hasColumn('movies', 'cast');
        foreach ($movies as $movie) {
            if (!$hasCastColumn) {
                unset($movie['cast']);
            }
            DB::table('movies')->updateOrInsert(
                ['slug' => $movie['slug']],
                $movie
            );
        }
    }
}
